version: '3.3'

services:

    aapanel:
        image: 'aapanel/aapanel:lib'
        container_name: aapanel
        restart: unless-stopped        
        ports:
            - '8200:7800'
            - '8021:21'
            - '8443:443'
            - '8300:80'
            - '8880:888'
        volumes:
            - ./website_data:/www/wwwroot
            - ./mysql_data:/www/server/data
            - ./vhost:/www/server/panel/vhost

